export function getQuotes() {
    return [
        "The only way to do great work is to love what you do.",
        "Strive not to be a success, but rather to be of value.",
        "The mind is everything. What you think you become.",
        "Believe you can and you're halfway there.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "It is during our darkest moments that we must focus to see the light.",
        "Do not go where the path may lead, go instead where there is no path and leave a trail.",
        "The best way to predict the future is to create it.",
        "The only impossible journey is the one you never begin.",
        "Success is not final, failure is not fatal: it is the courage to continue that counts.",
        "Innovation distinguishes between a leader and a follower.",
        "The journey of a thousand miles begins with a single step.",
        "What you get by achieving your goals is not as important as what you become by achieving your goals.",
        "The most difficult thing is the decision to act, the rest is merely tenacity.",
        "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.",
        "You are never too old to set another goal or to dream a new dream.",
        "The only person you are destined to become is the person you decide to be.",
        "Go confidently in the direction of your dreams! Live the life you have imagined.",
        "The greatest glory in living lies not in never falling, but in rising every time we fall.",
        "The true sign of intelligence is not knowledge but imagination.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "The harder you work for something, the greater you'll feel when you achieve it.",
        "Dream bigger. Do bigger.",
        "Don't stop when you're tired. Stop when you're done.",
        "Wake up with determination. Go to bed with satisfaction.",
        "Do something today that your future self will thank you for.",
        "Little things make big days.",
        "It's not about perfect. It's about effort.",
        "Great things never come from comfort zones.",
        "Push yourself, because no one else is going to do it for you.",
        "The only limit to our realization of tomorrow will be our doubts of today.",
        "The best way to predict the future is to invent it.",
        "The mind is not a vessel to be filled, but a fire to be kindled.",
        "The only true wisdom is in knowing you know nothing.",
        "The unexamined life is not worth living.",
        "Where there is love there is life.",
        "Only a life lived for others is a life worthwhile.",
        "The greatest wealth is to live content with little.",
        "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
        "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.",
        "It is not the critic who counts; not the man who points out how the strong man stumbles, or where the doer of deeds could have done them better.",
        "That’s one small step for man, one giant leap for mankind.",
        "We shall fight on the beaches, we shall fight on the landing grounds, we shall fight in the fields and in the streets, we shall fight in the hills; we shall never surrender.",
        "The very word 'secrecy' is repugnant in a free and open society."
    ];
}

export function getProgrammingSnippets() {
    return [
        "console.log('Hello, World!');",
        "function factorial(n) { if (n === 0) return 1; return n * factorial(n - 1); }",
        "const arr = [1, 2, 3, 4, 5]; arr.map(x => x * 2);",
        "class Animal { constructor(name) { this.name = name; } speak() { console.log(`${this.name} makes a noise.`); } }",
        "for (let i = 0; i < 10; i++) { console.log(i); }",
        "if (x > 5) { return true; } else { return false; }",
        "const sum = (a, b) => a + b;",
        "import React from 'react'; function App() { return <div>Hello React</div>; }",
        "public static void main(String[] args) { System.out.println('Java is fun!'); }",
        "print('Python rocks!')",
        "def fibonacci(n): a, b = 0, 1; while a < n: print(a, end=' '); a, b = b, a + b;",
        "let myPromise = new Promise((resolve, reject) => { setTimeout(() => resolve('Done!'), 1000); });",
        "const fetchData = async () => { try { const response = await fetch('https://api.example.com/data'); const data = await response.json(); console.log(data); } catch (error) { console.error('Error:', error); } };",
        "document.getElementById('myButton').addEventListener('click', () => { alert('Button clicked!'); });",
        "const numbers = [10, 20, 30, 40]; const total = numbers.reduce((acc, curr) => acc + curr, 0);",
        "function debounce(func, delay) { let timeout; return function(...args) { const context = this; clearTimeout(timeout); timeout = setTimeout(() => func.apply(context, args), delay); }; }",
        "const memoize = (fn) => { const cache = {}; return (...args) => { const key = JSON.stringify(args); if (cache[key]) return cache[key]; const result = fn(...args); cache[key] = result; return result; }; };",
        "SELECT * FROM users WHERE age > 18 ORDER BY name ASC;",
        "git clone <repository-url>",
        "npm install --save-dev webpack",
        "pip install requests",
        "try { int result = 10 / 0; } catch (Exception e) { System.out.println('Error: ' + e.getMessage()); }",
        "ArrayList<String> list = new ArrayList<>(); list.add('Item1'); list.add('Item2');",
        "const { useState, useEffect } = React; function Counter() { const [count, setCount] = useState(0); useEffect(() => { document.title = `Count: ${count}`; }, [count]); return <button onClick={() => setCount(count + 1)}>Count: {count}</button>; }",
        "std::cout << 'C++ is powerful!' << std::endl;",
        "class MyClass: def __init__(self, value): self.value = value; def get_value(self): return self.value;",
        "const express = require('express'); const app = express(); app.get('/', (req, res) => res.send('Hello Express!')); app.listen(3000, () => console.log('Server running on port 3000'));",
        "public interface MyInterface { void myMethod(); }",
        "func greet(name: String) -> String { return 'Hello, \(name)!' }",
        "var numbers = [1, 2, 3]; numbers.append(4);",
        "let data = { 'name': 'Alice', 'age': 30 }; console.log(data.name);",
        "const array1 = [1, 2, 3]; const array2 = [...array1, 4, 5];",
        "function sumAll(...args) { return args.reduce((acc, curr) => acc + curr, 0); }",
        "const { createStore } = Redux; const reducer = (state = 0, action) => { switch (action.type) { case 'INCREMENT': return state + 1; default: return state; } }; const store = createStore(reducer);",
        "CREATE TABLE products (id INT PRIMARY KEY, name VARCHAR(255), price DECIMAL(10, 2));",
        "UPDATE users SET email = 'new@example.com' WHERE id = 1;",
        "DELETE FROM orders WHERE status = 'completed';"
    ];
}

export function getSpeeches() {
    return [
        "Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal.",
        "I have a dream that one day this nation will rise up and live out the true meaning of its creed: We hold these truths to be self-evident, that all men are created equal.",
        "We choose to go to the Moon in this decade and do the other things, not because they are easy, but because they are hard, because that goal will serve to organize and measure the best of our energies and skills.",
        "Ask not what your country can do for you – ask what you can do for your country.",
        "The only thing we have to fear is fear itself.",
        "We shall fight on the beaches, we shall fight on the landing grounds, we shall fight in the fields and in the streets, we shall fight in the hills; we shall never surrender.",
        "It is not the critic who counts; not the man who points out how the strong man stumbles, or where the doer of deeds could have done them better.",
        "That’s one small step for man, one giant leap for mankind.",
        "The very word 'secrecy' is repugnant in a free and open society.",
        "We stand today on the edge of a new frontier. That frontier is not a set of promises; it is a set of challenges.",
        "Every generation needs a new revolution.",
        "Change will not come if we wait for some other person or some other time. We are the ones we've been waiting for. We are the change that we seek.",
        "If you're going through hell, keep going.",
        "Success is not final, failure is not fatal: it is the courage to continue that counts.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "It is better to be feared than loved, if you cannot be both.",
        "The only way to do great work is to love what you do.",
        "Strive not to be a success, but rather to be of value.",
        "The mind is everything. What you think you become.",
        "Believe you can and you're halfway there.",
        "It is during our darkest moments that we must focus to see the light.",
        "Do not go where the path may lead, go instead where there is no path and leave a trail.",
        "The best way to predict the future is to create it.",
        "The only impossible journey is the one you never begin."
    ];
}

export function getAIQuotes() {
    return [
        "The future of AI is not about robots replacing humans, but about empowering humans.",
        "Artificial intelligence is the new electricity.",
        "AI will be able to do everything that a human mind can do, and more.",
        "The biggest risk is not that AI will become sentient, but that we will treat it as such.",
        "AI is transforming every industry, making processes more efficient and intelligent.",
        "The ultimate promise of AI is to make our lives better, not to replace us.",
        "Don't worry that computers will get too smart and take over the world. Worry that they will get too stupid and take over the world.",
        "AI is the science of making machines do things that would require intelligence if done by men.",
        "The real question is not whether machines think, but whether men do.",
        "We are entering a new age of discovery, driven by artificial intelligence."
    ];
}
